version: '3.8'

services:
  gkh:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
    # volumes:
      # - ../backend:usr/gkh

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    restart: always

volumes:
  mongo-data:
    driver: local
