name: Commitlint Check

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @commitlint/{config-conventional,cli} --save-dev

      - name: Run Commitlint
        run: npx commitlint --from=HEAD~1
